/* CENTRAL_IO_H
 * 
 * author: Yuxuan Jiang | CS225 Group10
 * 
 * Description:
 * This file defines the IO haviour of the central heap 
 * 1. for receiving registrations from local registries.
 * 2. for report generating 
 * 
 */
#ifndef CENTRAL_IO_H
#define CENTRAL_IO_H
#include <fstream>
#include <string>
#include <queue>
#include <vector>
#include <fstream>
#include "../fibheap_f.h"
#include "../assqueue/assignment.h"
#include "../../ex1/relation.h"
using namespace std;

// TODO: ADD this class as a friend class of FibHeap
class CentralIO{
    public:
        CentralIO(FibHeap* n_vacc_heap, FibHeap* n_surg_heap, FibHeap* n_regi_heap, string n_path, Assignment* n_assignment)
                    : vacc_heap(n_vacc_heap)
                    , surg_heap(n_surg_heap)
                    , regi_heap(n_regi_heap)
                    , path(n_path)
                    , assignment(n_assignment) {};
        bool Read2Heap();   // This function reads registration information from files generated by local registries, the return value implies whether the operation succeeds
        bool ReportWeekly(int week,int key);
        bool ReportMonthly(int month, int key);
        bool compare(FibNode* a, FibNode* b, int key);
        void sortByKey(vector<FibNode*>&fiblist,int key);       //TODO sortbykey
        bool Write2File(vector<FibNode*>&print_list, int date, int type);

    private:
        // ======= Modification =======
        FibHeap* vacc_heap;   // heap for vaccination
        FibHeap* surg_heap;   // heap for surgery
        FibHeap* regi_heap;   // heap for regular registration
        // ======= Modification =======
        string path;
        Assignment* assignment;
        // vector<vector> register_arr;
        bool _WeeklyCured(int week, int key);
        bool _WeeklyAssigned(int week, int key);
        bool _WeeklyQueueing(int week, int key);
        bool _Monthly(int month, int key);
};


#endif