traversaltest: test.cpp graphtraversal.o graphtraversal.h
	g++ test.cpp graphtraversal.o -o traversaltest
graphtraversal.o: graphtraversal.cpp graphtraversal.h
	g++ -c graphtraversal.cpp -o graphtraversal.o